# Create a draft release when a tag is pushed
name: Create a release

on:
  # Allow manual trigger from the Actions tab:
  # https://github.com/Automattic/wp-openid-connect-server/actions/workflows/release.yml
  workflow_dispatch:

  push:
    tags: ['v*']

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install composer dependencies
        run: composer install --no-ansi --no-dev --no-interaction --no-plugins --no-scripts --optimize-autoloader

      - name: Generate readme.txt
        run: php bin/transform-readme.php

      - name: Create directory for release
        run: mkdir /tmp/release

      - name: Copy all files to release directory
        run: cp -r ./* /tmp/release/

      - name: Remove unnecessary files and directories
        run: |
          rm -rf /tmp/release/.github
          rm -rf /tmp/release/.git
          rm -rf /tmp/release/bin
          rm -rf /tmp/release/README.md
          rm -rf /tmp/release/.wp-env.json
          rm -rf /tmp/release/phpcs.xml

      - name: Move and rename release directory
        run: mv /tmp/release openid-connect-server

      - name: Create tar archive file for release
        run: tar -cvzf wp-openid-connect-server-${{ github.ref_name }}.tar.gz openid-connect-server

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          artifacts: "wp-openid-connect-server-${{ github.ref_name }}.tar.gz"
          artifactErrorsFailBuild: true
          draft: true
